### ISSUE TITLE
Confusing terms for Combat Result Win/Draw/Loss

### ISSUE THREAD

**Issue by thrasr** [VerveFEH/FEH-AI#2]
> https://vervefeh.github.io/FEH-AI/glossary.html
>5.a. Combat Result
>
>This tiebreaker only exists for attack evaluation. Assuming all else is equal, the attacker with the best combat result will have priority over other attackers. The three different results for combat are win, draw, and loss, whose priority is in that order. Any win is better than any draw, and any draw is better than any loss.

Win/Draw/Loss aren't defined anywhere as far as I can tell.  I want to assume that a Win is when the enemy is killed, a loss is that the attacker is killed, and a draw is neither is killed.  But it could easily be something like a win doing more damage than is returned.

Could this be updated to clarify?

Thanks for the awesome guide btw!

**Comment by bmzhu2** [comment]
Good catch, sorry for the delayed fix since I don't check the github page frequently.
